### ISSUE TITLE
Fail to see component in v.s. 2015 designer with Xamarin.Android.Support.Design

### ISSUE THREAD

**Issue by NadavHarari** [xamarin/AndroidSupportComponents#10]
When working with V.S 2015 Xamarin.
My  Main.axml Code:
<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.DrawerLayout 
  xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/drawer_layout"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:fitsSystemWindows="true">
    <include
        layout="@layout/include_list_viewpager" />
    <android.support.design.widget.NavigationView
        android:id="@+id/nav_view"
        android:layout_height="match_parent"
        android:layout_width="325dp"
        android:layout_gravity="start"
        android:fitsSystemWindows="true"
        app:headerLayout="@layout/nav_header"
        app:menu="@menu/drawer_view" />
</android.support.v4.widget.DrawerLayout>

The android.support.v4.widget.DrawerLayout  is marked with blue line under it and popup showing "android.support.v4.widget.DrawerLayout element is not declared".
When I switch to the Designer I nothing is shown.

Is this component version supports V.S2015 Designer?

**Comment by Redth** [comment]
I can't reproduce this on the current stable version of Xamarin.Android in VS2015 or VS2017, going to mark this one closed.
