### ISSUE TITLE
Android Architecture Components

### ISSUE THREAD

**Issue by JonZarate** [xamarin/AndroidSupportComponents#103]
Android is expanding their architecture toolset and I was wondering if any of those would be ported to Xamarin.Android (official documentation [here](https://developer.android.com/jetpack/arch/)). The list now contains:

- Data Binding
- Lifecycles
- LiveData
- Navigation
- Paging
- Room
- ViewModel
- WorkManager

I know that cross-platform solutions suit Xamarin better, but I think Xamarin.Android developers could benefit a lot of these native frameworks!

Any insight on this? Do these new tools push previous Arch Components' bindings ?

Thanks.

**Comment by kibotu** [comment]
i believe viewmodel, lifecycle and livedata can be used already

i'd love to use navigation though

**Comment by kibotu** [comment]
i've added a pull-request for Navigation #108

**Comment by newky2k** [comment]
PR #108 has been created and will be reviewed by the team
