### ISSUE TITLE
Build system depends on Mac

### ISSUE THREAD

**Issue by atsushieno** [xamarin/AndroidSupportComponents#105]
Android Support components are essential part of Xamarin.Android and should build everywhere, but the build system depends on macOS. The build failure outside Mac occurs as:

```
$CAKE_SETTINGS_SKIPVERIFICATION=true ./build.sh 
Feeds used:
  /home/atsushi/.nuget/packages/
  https://api.nuget.org/v3/index.json

All packages listed in /sources/xamarin/AndroidSupportComponents/tools/packages.config are already installed.
Error: One or more errors occurred.
	ApplicationName='/usr/bin/xcodebuild', CommandLine='-version', CurrentDirectory='/sources/xamarin/AndroidSupportComponents', Native error= Cannot find the specified file
```

**Comment by newky2k** [comment]
@atsushieno  The whole toolset has traditionally be built on macs, but we are trying to make them less reliant for build the source, but it will take time.

Thank you for your comments and hopefully in the future it will build on other systems too.
