### ISSUE TITLE
Arch.Navigation

### ISSUE THREAD

**Issue by kibotu** [xamarin/AndroidSupportComponents#106]
I've started to create a test project for later integration fo android architecture for navigation 

https://github.com/kibotu/Xamarin.Arch.Navigation

i can't get the navigation common to work. my understanding of xamarin jar binding is limited and i could use some help :)

when i try to build the nugets using msbuild (nuspec config is in solution file) i get the following errors:

>msbuild /p:Configuration="Release" 

```
"Arch.Navigation/Xamarin.Arch.Navigation/Xamarin.Arch.Navigation.sln" (default target) (1) ->
"Arch.Navigation/Xamarin.Arch.Navigation/arc-navigation/common/source/Xamarin.Arch.Navigation.Common.csproj" (default target) (2) ->
(CoreCompile target) ->
  obj/Release/generated/src/Androidx.Navigation.NavGraphNavigator.cs(9,23): error CS0534: 'NavGraphNavigator' does not implement inherited abstract member 'Navigator.CreateDestination()' [Arch.Navigation/Xamarin.Arch.Navigation/arc-navigation/common/source/Xamarin.Arch.Navigation.Common.csproj]
  obj/Release/generated/src/Androidx.Navigation.NavGraphNavigator.cs(9,23): error CS0534: 'NavGraphNavigator' does not implement inherited abstract member 'Navigator.Navigate(Object, Bundle, NavOptions)' [Arch.Navigation/Xamarin.Arch.Navigation/arc-navigation/common/source/Xamarin.Arch.Navigation.Common.csproj]
```

any ideas how to tackle this issue? 

kind regards
Jan

**Comment by kibotu** [comment]
ok i think i've figured out how to add them, please have a look at #108

**Comment by newky2k** [comment]
PR #108 has been created and will be reviewed by the team

**Comment by kibotu** [comment]
i had to stop on it due the resource folder 'navigation' was not supported by used android build tools from xamarin, other than that the binding seemed to be generated, no idea how well though, would love to have it available in xamarin
