### ISSUE TITLE
This class is missing : Android.Support.V4.App.NotificationCompat.MediaStyle

### ISSUE THREAD

**Issue by jonathanantoine** [xamarin/AndroidSupportComponents#109]
### Xamarin.Android Version (eg: 6.0):
Xamarin forms (latest)

### Operating System & Version (eg: Mac OSX 10.11):

Mac OS 10.11
### Support Libraries Version (eg: 23.3.0):
27.0.2

### Describe your Issue:
I cannot find this style : Android.Support.V4.App.NotificationCompat.MediaStyle

### Steps to Reproduce (with link to sample solution if possible):
Try to instanciate this class in code : Android.Support.V4.App.NotificationCompat.MediaStyle

### Include any relevant Exception Stack traces, build logs, adb logs:

> VS bug [#732430](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/732430)

**Comment by Redth** [comment]
At some point this must have been moved to `Android.Support.V4.Media.App.NotificationCompat.MediaStyle`. 

You can find it there :)
