### ISSUE TITLE
Release bindings for 24.2.0

### ISSUE THREAD

**Issue by martijn00** [xamarin/AndroidSupportComponents#11]
The Android Support libraries have gone through quite a change with 24.2. I would love to get my hands on it after it has been released for Xamarin!

**Comment by azchohfi** [comment]
Any ETA?

**Comment by Redth** [comment]
We are close to a preview release.  Keep in mind Android Support libraries v24.x will require that you compile your application against the Target Framework for API Level 24 (Nougat).

**Comment by kjeremy** [comment]
@Redth Looks like we can now target Nougat.

**Comment by martijn00** [comment]
How's that preview release going @Redth ?

**Comment by Redth** [comment]
Hey folks, some very early alpha releases finally went out to nuget.

`24.2.1-alpha1` will be the version number you find.

NOTE: There are some known regressions in v17-leanback with respect to some API's. 

Happy weekend!

**Comment by kjeremy** [comment]
Thanks @Redth.  Any time frame on when stable will be out?

**Comment by thomasvdb** [comment]
Eagerly waiting for v24 to fix this issue: https://code.google.com/p/android/issues/detail?id=78377

**Comment by Redth** [comment]
There will be a release candidate today while we wait for QA to finish internally. Pending any issues that QA uncovers this is the version we will release. Look for 24.2.1-rc1 later today.

**Comment by Redth** [comment]
You can grab the source code in master while we wait for the final review before release.

**Comment by Redth** [comment]
Finally, v24.2.1 is available on NuGet :)
