### ISSUE TITLE
ConstraintLayout 1.1.1

### ISSUE THREAD

**Issue by alexander-lysenko-88** [xamarin/AndroidSupportComponents#111]
Hi!
It's rather a question than an issue.

Google has recently released ConstraintLayout 1.1.1
https://androidstudio.googleblog.com/2018/06/constraintlayout-111.html
Do you have any planes to update the Xamarin Component as well, now on Nuget I can see 1.1.o only?

Thank you in advance!

**Comment by Redth** [comment]
1.1.2 is out now, we'll be working on bindings for them shortly.
