### ISSUE TITLE
Failed to resolve: com.android.support:cardview-v7:27.2.1

### ISSUE THREAD

**Issue by ajeetachal** [xamarin/AndroidSupportComponents#113]
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.example.ajeetachal.unus"
        minSdkVersion 21
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    buildToolsVersion '27.0.3'
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:27.2.1'
    implementation 'com.android.support:cardview-v7:27.2.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    implementation 'junit:junit:4.12'
    implementation 'com.android.support.test:runner:1.0.2'
    implementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.android.support:cardview-v7:27.2.1'
}
![screenshot 22](https://user-images.githubusercontent.com/22562104/43193254-2357da86-901d-11e8-9f3f-98e2cd05e125.png)

**Comment by Redth** [comment]
Hey there, this issue isn't really related to Xamarin at all, but it looks like you're trying to install a version of the support libraries which doesn't exist (`27.2.1`). Give`27.1.1` a try instead.
