### ISSUE TITLE
Missing method requireContext of non existing binding Android Support 21.1.0

### ISSUE THREAD

**Issue by quentinR0bert** [xamarin/AndroidSupportComponents#116]
Hi,

I was binding an Android Library but i have a little problem with the utilisation.

The last version of the library use the method requireContext wich was introduce in Android Support Library 27.1.0.
At the time, the last Xamarin Android Support is the 27.0.2.1

Do you have the idea of a date when a new version of Android Support will be release ? (27.1 or 27.1.1 or the new 28)

Thanks.

**Comment by newky2k** [comment]
@quentinR0bert  we are working on both 27.1.x and 28(which will be last version of support from Google before they switch to Android X)
