### ISSUE TITLE
AppCompatSeekBar - settiing Enabled and Thumb in axml has no effect

### ISSUE THREAD

**Issue by EnglishDave** [xamarin/AndroidSupportComponents#118]
### Steps to Reproduce (with link to sample solution if possible):
Create project.
Include Xamarin.Android.Support.Design 27.0.2.1 NuGet
Create layout (axml) containing AppCompatSeekBar.
Set Enabled to false in axml (e.g. android:Enabl;ed="false")
Set thumb drawable to a drwabled in axml (e.g. android:thumb="@drawable/ic_menu_camera"
Build and run
SeekBar still enabled and still has default thumb.

In code, set the Enabled property to false; and set thumb drawable [e.g. SetThumb(ContextCompat.GetDrawable(Activity, Resource.Drawable.ic_menu_camera)); ]
Build and run
SeekBar still disabled and thumb changed.

**Comment by newky2k** [comment]
@EnglishDave could you please provide a sample that demonstrates the issue you are experiencing please.

Regards

**Comment by Redth** [comment]
No response received, unable to reproduce, closing issue.  Please open a new issue if you have more information.
