### ISSUE TITLE
TextInputLayout not support method setDefaultHintTextColor, setErrorTextColor

### ISSUE THREAD

**Issue by rsgrey** [xamarin/AndroidSupportComponents#119]
### Xamarin.Android Version:
Xamarin.Android 9.0.19

### Operating System & Version:
Windows 10

### Support Libraries Version:
28.0.0-preview

### Describe your Issue:
TextInputLayout in Xamarin does not support method setDefaultHintTextColor, setErrorTextColor

Sample Java: 
```
TextInputLayout text = findViewById(R.id.text);
text.setDefaultHintTextColor(color);
```
It is very important for me

**Comment by newky2k** [comment]
@rsgrey could please provide a sample project which demonstrates the issue you've reported

Regards

**Comment by newky2k** [comment]
@rsgrey  Xamarin please

**Comment by rsgrey** [comment]
Sorry, I am stupid. Compilation Version was not 9.0.

**Comment by newky2k** [comment]
@rsgrey Thats good news, that you found the issue

Regards
