### ISSUE TITLE
Release bindings for ConstraintLayout

### ISSUE THREAD

**Issue by borgdylan** [xamarin/AndroidSupportComponents#12]
Please add bindings for the new constraint layout library. Google are already recommending it for day to day use.

**Comment by borgdylan** [comment]
Ping

**Comment by Redth** [comment]
Working on this, there's a branch with the bindings that's going to get merged in to the 24.2.1 branch shortly, and that will be merged to master shortly after.

https://github.com/xamarin/androidsupportcomponents/tree/support-constraints

**Comment by borgdylan** [comment]
Thank you @Redth . I will be testing(jus the library as I use teh designer that comes with android studio for Xamamrin already) this once it is available.

**Comment by Redth** [comment]
@borgdylan these are up now in master: 
https://github.com/xamarin/AndroidSupportComponents/tree/master/constraint-layout
https://github.com/xamarin/AndroidSupportComponents/tree/master/constraint-layout-solver

Also on NuGet:
https://www.nuget.org/packages/Xamarin.Android.Support.Constraint.Layout
https://www.nuget.org/packages/Xamarin.Android.Support.Constraint.Layout.Solver

They are based on the Alpha9 release from Google (unfortunately Google is currently releasing these as their own packages in their SDK manager, out of band of the Support Library m2repository archive).

Please open a new issue if you run into any problems with them.

**Comment by borgdylan** [comment]
Thank you very much!
