### ISSUE TITLE
NU3008: The package integrity check failed.

### ISSUE THREAD

**Issue by anoorally** [xamarin/AndroidSupportComponents#120]
### Xamarin.Forms Version (eg: 6.0):
2.5.1

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10

### Support Libraries Version (eg: 23.3.0):
25.4.0.2

### Describe your Issue:
"NU3008: The package integrity check failed", when updating support libraries from 25.4.0.2 to 27.0.2.1 

### Steps to Reproduce (with link to sample solution if possible):
- Go to Update Tab
- Select Android support libraries
   - Xamarin.Android.Support.Compat
   - Xamarin.Android.Support.Design
   - Xamarin.Android.Support.v7.AppCompat
   - Xamarin.Android.Support.v4
   - Xamarin.Android.Support.v7.CardView
   - Xamarin.Android.Support.v7.MediaRouter
- Click Update

### Include any relevant Exception Stack traces, build logs, adb logs:
Installing Xamarin.Android.Support.Transition 27.0.2.1.
Signature Hash Algorithm: SHA256
NU3008: The package integrity check failed.
Signature type: Author

> VS bug [#733082](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/733082)

**Comment by newky2k** [comment]
@anoorally Do you get the same thing if you add them directly, rather than upgrading?  How old are you project and solution files?

I'm assigning @Redth  to look into it for you.

**Comment by anoorally** [comment]
@newky2k 
- I tried adding directly, I still get the integrity check error in the console.
- The project was created last week (08.10.18) for prototyping [VS 2017 Preview | Xamarin .NET Shared | Xamarin.Forms 2.5.1]

**Comment by newky2k** [comment]
@anoorally Thanks for the update  Hopefully @Redth  will be able to find something

**Comment by newky2k** [comment]
@anoorally  Additionally, could you try clearing the packages out of your nuget cache.  This will force the IDE to redownload them afresh.  If they were some how corrupted during the first download, the IDE might not redownload them.

Regards

**Comment by Redth** [comment]
Closing due to lack of response.  If you have more information please open a new issue and reference this one in it.
