### ISSUE TITLE
Add bindings for android.arch.work

### ISSUE THREAD

**Issue by JudahSoftware** [xamarin/AndroidSupportComponents#126]
> VS bug [#733083](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/733083)

**Comment by basiljohntme** [comment]
Could you please look for android.arch.work » work-runtime, android.arch.work » work-firebase & android.arch.persistence.room » runtime as well? 
Thank you

**Comment by jom16antonio** [comment]
Any updates on this? How can you make WorkManager work with Xamarin?

**Comment by basiljohntme** [comment]
Hi @Redth, Do you know when will the android.arch.work related libraries available to use? 
I have an android binding project which is dependent on these libraries. 
Thank you

**Comment by Redth** [comment]
Closing this, we released bindings a little while back for Work Manager API's.
