### ISSUE TITLE
Does NavigationEvent work?

### ISSUE THREAD

**Issue by Rolf88** [xamarin/AndroidSupportComponents#13]
### Xamarin.Android Version (eg: 6.0):
7.0.1.2

### Operating System & Version (eg: Mac OSX 10.11):
windows 10

### Support Libraries Version (eg: 23.3.0):
23.4.0.1

### Describe your Issue:
Tried the sample for customtabs, can't get navigationEvent to be called!!
Is this just me? does the navigationevent actually work for others in the sample?

**Comment by Redth** [comment]
Basically, OnNavigationEvent was not marked as an override, so it wasn't being called.
