### ISSUE TITLE
AndroidX Bindings

### ISSUE THREAD

**Issue by Redth** [xamarin/AndroidSupportComponents#130]
We need to get a baseline set of AndroidX bindings compiling to be able to possibly release as preview, and to start comparing API diffs from Android Support 28.x (we'll have to write something to compare diffs with the namespace changes in mind).

> VS bug [#736475](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/736475)

**Comment by Redth** [comment]
This work is generally happening on this branch: https://github.com/xamarin/AndroidSupportComponents/tree/AndroidX

**Comment by jom16antonio** [comment]
Any updates on this? How can you make WorkManager work with Xamarin?

**Comment by AlexanderMelchers** [comment]
@Redth, @jom16antonio

Is there any more information on when AndroidX will be available for use with Xamarin.Android?

Thanks for your help!

Best regards,
Alexander.
