### ISSUE TITLE
BottomNavigationView new props inaccessible 

### ISSUE THREAD

**Issue by ThomasDhaen** [xamarin/AndroidSupportComponents#137]
### Xamarin.Android Version (eg: 6.0):
9.1.0

### Operating System & Version (eg: Mac OSX 10.11):
macOS

### Support Libraries Version (eg: 23.3.0):
28.0.0

### Describe your Issue:
Some new functions / props aren't available

### Steps to Reproduce (with link to sample solution if possible):
- Install latest android design support packages
- Add BottomNavigationView to a view
+ Adding `app:itemIconSize=15dp` in XML doesn't work => `[APT0000] No resource identifier found for attribute 'itemIconSize' in package 'app_id'`
+ Trying to set the values programatically doesn't work, unknown function/prop.

**Comment by Redth** [comment]
Thanks, we're looking into this.

**Comment by moljac** [comment]
Here is my repo with 4 samples ported from various java samples on github. Ports are not complete, but 2 projects do launch:

-  NealRDC
-  vipulasr

You will see I use `app:itemIconSize=15dp` in the layout file and reading the size out in the code of the `MainActivity.cs`

Here is the repo:
https://github.com/moljac/Xamarin.Android.Samples/tree/master/samples/Android.Support/BottomNavigationView

NOTE 1: other 2 projects are more complex and in one I'm having issues with resources for CardView, but this is not your issue.

NOTE 2: There is still stuff to do and I'll finish those in next few days. Together with automatic cake script for building all samples.

Thus:
Leaving this one in Low Priority. Issue will be closed when all samples are done and show no issues.

**Comment by moljac** [comment]
@ThomasDhaen ^^ (sorry forgot to mention you)

**Comment by moljac** [comment]
Closing the issue after porting 4 samples from java to C#:

https://github.com/moljac/Xamarin.Android.Samples/tree/master/samples/Android.Support/BottomNavigationView

Reopen the issue if necessary.
