### ISSUE TITLE
AndroidX: Create jetifier invocation wrapper

### ISSUE THREAD

**Issue by Redth** [xamarin/AndroidSupportComponents#145]
Goals:
- Create a java based wrapper around the jetifier library which we can use to invoke jetifier itself via CLI
- One JVM instance should be able to process multiple .jar files specified

> VS bug [#773871](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/773871)

**Comment by SotoiGhost** [comment]
Does this kind of satisfy this task or I'm getting wrong the task?

https://developer.android.com/studio/command-line/jetifier
