### ISSUE TITLE
Bump RenderScript library version to 28.0.0.1

### ISSUE THREAD

**Issue by Im-PJ** [xamarin/AndroidSupportComponents#150]
### Xamarin.Android Version (eg: 6.0):
9.1.5.0

### Operating System & Version (eg: Mac OSX 10.11):
VS 2017, Windows 10

### Support Libraries Version (eg: 23.3.0):
28.0.0.1

### Describe your Issue:
I'm using Telerik Xamarin controls targeting Android Pie and they depend heavily on android support libraries. One of the Xamarin.Android.Support.v8.RenderScript is having only latest version as 27.0.2.1 whereas all other support libraries are at 28.0.0.1. As all the support libraries needs to be at same version, Im unable to install renderscript and use Telerik Controls. My only choice is to downgrade everything to 27.0.2.1 which will force me to target only Oreo 8.1 
May I know when Renderscript will be updated to SDK 28 or is it not being supported anymore?

> VS bug [#805950](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/805950)

**Comment by Redth** [comment]
Thanks, we're working on an update for this as well.

**Comment by Szymaniuk** [comment]
Any update on that? It's still 27.0.2.1.

**Comment by Redth** [comment]
https://www.nuget.org/packages/Xamarin.Android.Support.v8.RenderScript/28.0.0.1

Sorry for the delay, this should help!
