### ISSUE TITLE
Unable to Resolve MenuCompat SetGroupDividerEnabled

### ISSUE THREAD

**Issue by masterwok** [xamarin/AndroidSupportComponents#151]
### Xamarin.Android Version (eg: 6.0):
I feel stupid, I don't know what this is referring to after looking at my NuGet packages. How do I find this?

### Operating System & Version (eg: Mac OSX 10.11):

Mac OS 10.14.2

### Support Libraries Version (eg: 23.3.0):
28.0.0.1

### Describe your Issue:
I'm trying to set the group divider in a menu but I'm unable to resolve MenuCompat.setGroupDividerEnabled(Menu menu, boolean enabled) as defined [here](https://developer.android.com/reference/android/support/v4/view/MenuCompat).

I've tried referencing the v4 support libraries.

### Steps to Reproduce (with link to sample solution if possible):
Try to reference the method.

### Include any relevant Exception Stack traces, build logs, adb logs:
Not relevant.

**Comment by Redth** [comment]
Hey there, make sure you install Xamarin.Android.Support.Compat nuget.  I can see the API exists there.

**Comment by masterwok** [comment]
Thank you, I'll try that!
