### ISSUE TITLE
WorkManager's methods return type is different from Android's documentation.

### ISSUE THREAD

**Issue by xyfoo** [xamarin/AndroidSupportComponents#169]
### Package

Xamarin.Android.Arch.Work.Runtime 1.0.0

### Issue

```AndroidX.Work.WorkManager.GetWorkInfosByTagLiveData``` method only return ```LiveData``` instead of ```LiveData<List<WorkInfo>```, as stated in the [AndroidX's documentation for the method](https://developer.android.com/reference/androidx/work/WorkManager#getWorkInfosByTagLiveData(java.lang.String)).

![image](https://user-images.githubusercontent.com/12484975/57213062-3a3b4680-7018-11e9-977e-342d738979ea.png)

Current method's metadata as displayed in Visual Studio 2017.

```csharp
[Register("getWorkInfosByTagLiveData", "(Ljava/lang/String;)Landroid/arch/lifecycle/LiveData;", "GetGetWorkInfosByTagLiveData_Ljava_lang_String_Handler")]
public abstract LiveData GetWorkInfosByTagLiveData(string p0);
```

By not having a typed LiveData object, we would not be able to retrieve the value of the LiveData as below:

```csharp
LiveData myLiveData = WorkManager.Instance.GetWorkInfosByTagLiveData("myTag");

// The following will fail as LiveData.Value will return a Java.Lang.Object item
// and the conversion will be unsuccessful.

List<WorkInfo> workInfos = (List<WorkInfo>)myLiveData.Value;
```
#### WorkManager methods with the same issue

* GetWorkInfosByTagLiveData
* GetWorkInfoByIdLiveData
* GetWorkInfosForUniqueWorkLiveData

### Version

* Xamarin.Android: 9.1.7.0
* Operating System & Version: Win 10 Enterprise 1607 (Build 14393.2906)
* Support Libraries: 28.0.0.1

**Comment by Redth** [comment]
Try using `.JavaCast<T>` in this case:

```
var workInfos = myLiveData.Value.JavaCast<List<WorkInfo>>();
```

**Comment by yelinzh** [comment]
> Try using `.JavaCast<T>` in this case:
> 
> ```
> var workInfos = myLiveData.Value.JavaCast<List<WorkInfo>>();
> ```

Hi! The code caused the following exception. How to deal with it?
```
The type 'System.Collections.Generic.IList<AndroidX.Work.WorkInfo>' cannot be used as type parameter 'TResult' in the generic type or method 'Extensions.JavaCast<TResult>(IJavaObject)'. There is no implicit reference conversion from 'System.Collections.Generic.IList<AndroidX.Work.WorkInfo>' to 'Android.Runtime.IJavaObject'.
```
