### ISSUE TITLE
Method requireContext() haven't been added into Xamarin.Android.Support.Fragment 28.0.0.1

### ISSUE THREAD

**Issue by Hasdik** [xamarin/AndroidSupportComponents#180]
### Xamarin.Android Version (eg: 6.0):
Xamarin.Android.Support.Fragment v28.0.0.1 

### Describe your Issue:
According to the support library changelog and the Fragment class documentation (https://developer.android.com/reference/android/support/v4/app/Fragment.html), there are now new methods like requireContext().

But I couldn't find the method requireContext() in xamarin android.

Many SDK(andriod) use method requireContext(), log: http://joxi.ru/DrlGMDVTVQ8aoA 

Can you add this method?

**Comment by Redth** [comment]
It's there for the API 28 support, please make sure you are setting your target framework version to MonoAndroid90 (API 28) or higher as the 28.0.0.x packages are multitargeted, so the .dll your app actually consumes depends on the target framework version you've set in your project.
