### ISSUE TITLE
NavigationClick event of Android.Support.V7.Widget.Toolbar is missing

### ISSUE THREAD

**Issue by sergeylutski** [xamarin/AndroidSupportComponents#19]
### Describe your Issue:

In Xamarin.Android.Support.v7.AppCompat library for some reasons NavigationClick event of Android.Support.V7.Widget.Toolbar class is missing. I see that it's commented in corresponding addition class in source code of bindings: https://github.com/xamarin/AndroidSupportComponents/blob/master/v7-appcompat/source/Additions/Toolbar.cs. It seems to be a bug. Can you clarify this please?
### Include any relevant Exception Stack traces, build logs, adb logs:

Error CS1061: Type 'Android.Support.V7.Widget.Toolbar' does not contain a definition for 'NavigationClick' and no extension method 'NavigationClick' of type 'Android.Support.V7.Widget.Toolbar' could be found. Are you missing an assembly reference?

**Comment by Redth** [comment]
Yes, this will be brought back in v25.0.1-rc2 or greater, thanks!
