### ISSUE TITLE
Update to revision v25.0

### ISSUE THREAD

**Issue by martijn00** [xamarin/AndroidSupportComponents#20]
Android Support Library, revision 25.0.0 (October 2016) has been released: https://developer.android.com/topic/libraries/support-library/revisions.html

**Comment by martijn00** [comment]
@Redth Can we have a preview of this on Nuget?

**Comment by Redth** [comment]
Sorry, this one's taken awhile since we are moving to a new mechanism for working with the actual .aar files at app compile time.  We have v25.0.1-rc1 out on NuGet now.

**Comment by Redth** [comment]
Closing this as 25.1.0-beta2 is on track to go stable at this point.
