### ISSUE TITLE
Error XA2002: Can not resolve reference: `Xamarin.Android.Support.v4`, referenced by `com.refractored.monodroidtoolkit`. Please add a NuGet package or assembly reference for `Xamarin.Android.Support.v4`, or remove the reference to `com.refractored.monodroidtoolkit`. (XA2002) 

### ISSUE THREAD

**Issue by hadigityat** [xamarin/AndroidSupportComponents#202]
### Xamarin.Android Version (eg: 6.0):
Version: 9.4.1.0 (Visual Studio Community)
Commit: xamarin-android/d16-2/ebd65c9
Android SDK: /Users/Can/Downloads/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.2
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: mono/mono/2019-02@e6f5369c2d2
Java.Interop: xamarin/java.interop/d16-2@d64ada5
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

### Operating System & Version (eg: Mac OSX 10.11):
Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Tue Aug 20 16:57:14 PDT 2019
    root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

### Support Libraries Version (eg: 23.3.0):

  <package id="Xamarin.AndroidX.Annotation" version="1.0.2-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.AppCompat" version="1.0.2-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.Arch.Core.Common" version="2.0.1-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.Arch.Core.Runtime" version="2.0.1-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.AsyncLayoutInflater" version="1.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.CardView" version="1.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.Collection" version="1.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.ConstraintLayout" version="1.1.3-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.ConstraintLayout.Solver" version="1.1.3-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.CoordinatorLayout" version="1.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.Core" version="1.0.1-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.CursorAdapter" version="1.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.CustomView" version="1.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.DocumentFile" version="1.0.1-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.DrawerLayout" version="1.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.Fragment" version="1.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.GridLayout" version="1.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.Interpolator" version="1.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.Legacy.Preference.V14" version="1.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.Legacy.Support.Core.UI" version="1.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.Legacy.Support.Core.Utils" version="1.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.Legacy.Support.V4" version="1.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.Lifecycle.Common" version="2.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.Lifecycle.Extensions" version="2.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.Lifecycle.LiveData" version="2.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.Lifecycle.LiveData.Core" version="2.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.Lifecycle.Process" version="2.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.Lifecycle.Runtime" version="2.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.Lifecycle.Service" version="2.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.Lifecycle.ViewModel" version="2.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.Loader" version="1.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.LocalBroadcastManager" version="1.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.Media" version="1.0.1-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.Preference" version="1.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.Print" version="1.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.RecyclerView" version="1.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.SlidingPaneLayout" version="1.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.SwipeRefreshLayout" version="1.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.Transition" version="1.0.1-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.VectorDrawable" version="1.0.1-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.VectorDrawable.Animated" version="1.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.VersionedParcelable" version="1.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.AndroidX.ViewPager" version="1.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.Build.Download" version="0.4.11" targetFramework="monoandroid90" />
  <package id="Xamarin.Firebase.Common" version="71.1610.0" targetFramework="monoandroid90" />
  <package id="Xamarin.Firebase.Iid" version="71.1710.0" targetFramework="monoandroid90" />
  <package id="Xamarin.Firebase.Iid.Interop" version="71.1601.0" targetFramework="monoandroid90" />
  <package id="Xamarin.Firebase.Measurement.Connector" version="71.1701.0" targetFramework="monoandroid90" />
  <package id="Xamarin.Firebase.Messaging" version="71.1740.0" targetFramework="monoandroid90" />
  <package id="Xamarin.Google.Android.Material" version="1.0.0-preview02" targetFramework="monoandroid90" />
  <package id="Xamarin.Google.AutoValue.Annotations" version="1.6.5" targetFramework="monoandroid90" />
  <package id="Xamarin.GooglePlayServices.Base" version="71.1610.0" targetFramework="monoandroid90" />
  <package id="Xamarin.GooglePlayServices.Basement" version="71.1620.0" targetFramework="monoandroid90" />
  <package id="Xamarin.GooglePlayServices.Location" version="71.1600.0" targetFramework="monoandroid90" />
  <package id="Xamarin.GooglePlayServices.Maps" version="71.1610.0" targetFramework="monoandroid90" />
  <package id="Xamarin.GooglePlayServices.Places.PlaceReport" version="71.1600.0" targetFramework="monoandroid90" />
  <package id="Xamarin.GooglePlayServices.Stats" version="71.1601.0" targetFramework="monoandroid90" />
  <package id="Xamarin.GooglePlayServices.Tasks" version="71.1601.0" targetFramework="monoandroid90" /> 

### Describe your Issue:
Getting build errors for monodroidtoolkit, Xamarin.Firebase and Xamarin.GooglePlayServices libraries which seem to use older support libraries.

There needs to be updated versions of the problematic libraries(listed below, and there could be more) using the AndroidX support libs instead.  

### Steps to Reproduce (with link to sample solution if possible):
Use AndroidX libraries in conjunction with com.refractored.monodroidtoolkit, Xamarin.Firebase.Iid <Xamarin.Android.Support.Core.Utils missing>, Xamarin.GooglePlayServices.Base<Xamarin.Android.Support.Fragment missing>, Xamarin.GooglePlayServices.Basement<Xamarin.Android.Support.Fragment missing>, Xamarin.GooglePlayServices.Maps<Xamarin.Android.Support.Fragment missing>, Xamarin.GooglePlayServices.Stats <Xamarin.Android.Support.Core.Utils missing>

**Comment by repallekiran** [comment]
Hi Hadigityat
I am getting the same error while building. Can you please explain how can I resolve this issue.
