### ISSUE TITLE
Started getting warnings after updating to 28.0.0.3

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/AndroidSupportComponents#203]
I started seeing the below warnings after I updated my support packages from 28.0.0.1 to 28.0.0.3. Any recommendation to resolve these?

> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3277: Found conflicts between different versions of "System.Net.Http" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.

> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1755,2): warning XA0106: Skipping MyApp.Droid.Resource.Id.main_scrollview. Please check that your Nuget Package versions are compatible.

> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1755,2): warning XA0106: Skipping MyApp.Droid.Resource.Id.shellcontent_scrollview. Please check that your Nuget Package versions are compatible.

**Comment by Redth** [comment]
I'm not sure these are related to 28.0.0.3 at all.  Can you double check with 28.0.0.1 that you don't see these? 

The last two you can definitely safely ignore, and I believe the first one is ok to ignore as well.

**Comment by adrianknight89** [comment]
Sorry, I think you may be right. I looked again and can't verify that these warnings are due to the updates.
