### ISSUE TITLE
Version conflict detected between Xamarin.Android.Support 28.0.0.3 and Xamarin.Android.Arch.Work.Runtime 1.0.0

### ISSUE THREAD

**Issue by tranb3r** [xamarin/AndroidSupportComponents#204]
There is a version conflict between the newly released Xamarin.Android.Support 28.0.0.3 and Xamarin.Android.Arch.Work.Runtime 1.0.0
Could you please fix dependencies in Xamarin.Android.Arch.Work.Runtime and publish a new version of it ?

---

Xamarin.Forms 4.3.0.819712-pre2 
->      Xamarin.Android.Support.CustomTabs      28.0.0.3 
->      Xamarin.Android.Support.Core.UI              28.0.0.3      
->      Xamarin.Android.Support.Core.Utils          28.0.0.3 
->      Xamarin.Android.Support.Loader              28.0.0.3      
->      Xamarin.Android.Arch.Lifecycle.LiveData    1.1.1.3 
->      Xamarin.Android.Arch.Core.Common (=    1.1.1.3)  

Xamarin.Android.Arch.Work.Runtime 1.0.0      
->      Xamarin.Android.Arch.Lifecycle.Extensions  1.1.1.1 
->      Xamarin.Android.Arch.Core.Common (=     1.1.1.1)

**Comment by Redth** [comment]
https://www.nuget.org/packages/Xamarin.Android.Arch.Work.Runtime/1.0.0.3 should fix this
