### ISSUE TITLE
MotionLayout.ITransitionListener missing parameter names

### ISSUE THREAD

**Issue by Cheesebaron** [xamarin/AndroidSupportComponents#225]
### Support Libraries Version (eg: 23.3.0):
Xamarin.Android.Support.Constraint.Layout 2.0.0-beta2
Xamarin.Android.Support.Constraint.Layout.Solver 2.0.0-beta2

### Describe your Issue:
The interface ITransitionListner just has p0, p1, p2, p3 as names for the arguments you can pass into the method it defines.

```csharp
void OnTransitionChange(MotionLayout p0, int p1, int p2, float p3)
void OnTransitionCompleted(MotionLayout p0, int p1)
void OnTransitionStarted(MotionLayout p0, int p1, int p2)
void OnTransitionTrigger(MotionLayout p0, int p1, bool p2, float p3)
```

I would expect them to be:

```csharp
void OnTransitionChange(MotionLayout motionLayout, int startId, int endId, float progress) 
void OnTransitionCompleted(MotionLayout motionLayout, int currentId) 
void OnTransitionStarted(MotionLayout motionLayout, int startId, int endId) 
void OnTransitionTrigger(MotionLayout motionLayout, int triggerId, bool positive, float progress) 
```

See: https://developer.android.com/reference/androidx/constraintlayout/motion/widget/MotionLayout.TransitionListener

### Steps to Reproduce (with link to sample solution if possible):
1. Add `Xamarin.Android.Support.Constraint.Layout` 2.0.0-beta2
2. Implement `MotionLayout.ITransitionListener`: `private class MotionLayoutListener : Java.Lang.Object, MotionLayout.ITransitionListener`
3. Ask VS to implement methods

**Comment by moljac** [comment]
1st:  Sometimes parameter names must be added manually and it takes time.

2nd: this seems to be AndroidX issue and AndroidX has new repo.

Would you be so kind and move this issue to AndroidX repo (close it here and [re]open it in AndroidX)?
THanks
