### ISSUE TITLE
Cannot install pakage in VS2015 community with all latest updates

### ISSUE THREAD

**Issue by onedevteam** [xamarin/AndroidSupportComponents#23]
I'm trying to install package with nuget PM, but i'm getting error message: 

> Could not install package 'Xamarin.Android.Support.Compat 24.2.1'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by Tom741** [comment]
I have the exact same issue on a fresh project. I just installed Xamarin few days ago (just starting with it).

**Comment by kvart714** [comment]
+1

**Comment by tragram** [comment]
+1
Just install the previous version, that one works...

**Comment by CSkoubo** [comment]
If you guys upgrade to target v7 (api 24) it will work.

**Comment by markmadlangbayan** [comment]
Any way we can support Android v6?

**Comment by kvart714** [comment]
I have a target version 7.0. But it does not help. I get an error
"...You are trying to install this package into a project that targets 'MonoAndroid, Version = v7.0', but the package..."

**Comment by brazilianldsjaguar** [comment]
+1, just got things up and running. I'll try the v7 (api24) and see if I can get it to go. Thanks.

**Comment by Redth** [comment]
As mentioned earlier in this thread, you need to set your Target Framework of your project to v7.0 (API Level 24) or higher to consume these libraries.

We are (finally) starting to follow Google's guidelines which are that your _compileSdkVersion_ (in our terminology, _Target Framework_) must match the major version number of the support libraries you are referencing.  This means, _v24.2.1_ has a major version number of _24_, which can only be used by projects compiling against _API Level 24_.

**Comment by kvart714** [comment]
I HAVE A TARGET VERSION 7.0 (API LVL 24). BUT IT DOESN'T HELP. I GET AN ERROR
"...You are trying to install this package into a project that targets 'MonoAndroid, Version = v7.0', but the package..."

**Comment by CSkoubo** [comment]
@kvart714 are you sure you target API 24 in all your droid projects?

**Comment by kvart714** [comment]
@CSkoubo yes, I create a new project, set the target API 24, rebuild the project and try to add NuGet package but get an error.
I can still manually download the package and install it offline. But then I get errors with other libraries (eg 'Could not load assembly' Xamarin.Android.Support.Core.UI ')

**Comment by mouseymickey2** [comment]
How can we target Android 6? How can we us NuGet to get version 23 of the AndroidSupportComponents? We are targeting Android 6, because we don't expect a Android 7 update for our devices in a timely manner.

**Comment by Redth** [comment]
Your app can still run on lower API levels than 24 if you set your minimum sdk version to be a lower version, but your Target Framework will need to be 24 or higher to use version 24.x of Android Support Libraries.  For more information on API Levels, take a look at this article: https://medium.com/google-developers/picking-your-compilesdkversion-minsdkversion-targetsdkversion-a098a0341ebd
