### ISSUE TITLE
Will Xamarin.Google.Android.Material.Dialog be included in the package?

### ISSUE THREAD

**Issue by georgi8706** [xamarin/AndroidSupportComponents#232]
Hello Guys,
I see that some namespaces, like Xamarin.Google.Android.Material.Dialog, are missing from the package. Does this mean that they are still not added and will be added in future releases?

**Comment by moljac** [comment]
@georgi8706 
Hi I need some more info:

> I see that some namespaces, like Xamarin.Google.Android.Material.Dialog, are missing from the package.

Which package are you referring to?

**Comment by moljac** [comment]
Seems like this is in v 1.1.0 and it is still prerelease 

https://github.com/material-components/material-components-android/releases/tag/1.1.0-alpha02

**Comment by moljac** [comment]
Nope. Not found in jar after decompiling v.1.0.0.

**Comment by georgi8706** [comment]
I don't know in which package it should be. In android the class MaterialAlertDialogBuilder is in com.google.android.material.dialog package. I have a nuget package on my machine Xamarin.Google.Android.Material with version 1.1.0 preview06.

**Comment by moljac** [comment]
Closing this one. 

It will be in AndroidX (another repo) and  version 1.1.0

**Comment by georgi8706** [comment]
Thanks.
