### ISSUE TITLE
WorkManager - missing getWorkInfosForUniqueWork

### ISSUE THREAD

**Issue by todorspetkov** [xamarin/AndroidSupportComponents#233]
### Describe your Issue:
Why is getWorkInfosForUniqueWork missing in bindings?

**Comment by moljac** [comment]
@todorspetkov 

A little bit more info perhaps? Nuget version, etc.

**Comment by todorspetkov** [comment]
Hi, sorry. Here you go:
Target Android Version : 10 (API level 29)
Operating System & Version : Mac Mojave 10.14.6
Support Libraries Version : 28.0.0.3
WorkManager nuget version : Xamarin.Android.Arch.Work.Runtime 1.0.0.3
Describe your Issue:
When writing native java code for Android we used the method getWorkInfosForUniqueWork to obtains status of already scheduled work. This method is not present in the Xamarin Android bindings for the library. We tried to use the method GetWorkInfosForUniqueWorkLiveData but when we try to extract the WorkInfo list from it the result is always null. Here is how we use the live data method :
LiveData statuses = AndroidX.Work.WorkManager.Instance.GetWorkInfosForUniqueWorkLiveData(JOB_TAG);
JavaList<AndroidX.Work.WorkInfo> workInfoList = statuses.Value.JavaCast<JavaList<AndroidX.Work.WorkInfo>>();

Since in Android native java we used  getWorkInfosForUniqueWork I was wondering  why this method is not mapped in the bindings...
Otherwise is there a blocking call that we can make to get scheduled jobe WorkInfo?
Thanks,
    Tod

**Comment by moljac** [comment]
@todorspetkov 
Seems like this is AndrodiX:
```
LiveData statuses = AndroidX.Work.WorkManager.Instance.GetWorkInfosForUniqueWorkLiveData(JOB_TAG);
JavaList<AndroidX.Work.WorkInfo> workInfoList = statuses.Value.JavaCast<JavaList<AndroidX.Work.WorkInfo>>();
```

Please close this issue here and reopen it in AndroidX.

it has generic return type and thus it was not surfaced.

**Comment by todorspetkov** [comment]
Closing. Will move to AndroidX.

**Comment by LorenzoAlfaro** [comment]
> Closing. Will move to AndroidX.

Where can I follow this issue?

**Comment by todorspetkov** [comment]
AndroidX already exposes GetWorkInfosForUniqueWork and so there is nothing to follow. As I understood it if one wants to use these calls one has to migrate the whole project to AndroidX...
