### ISSUE TITLE
When will Xamarin Studio support constraint layout ?

### ISSUE THREAD

**Issue by apg-sattha** [xamarin/AndroidSupportComponents#24]
This layout is worth for drag like Auto Layout not write in .axml. So, I want to know do you have any plan on full support this Layout in Xamarin Studio ?

**Comment by Redth** [comment]
Please file an issue at http://bugzilla.xamarin.com 
This repository only has to do with the bindings for those libraries, not the actual integration into the designer, so I cannot speak to that.
