### ISSUE TITLE
Too many field references

### ISSUE THREAD

**Issue by AlexanderOsokin** [xamarin/AndroidSupportComponents#26]
### Xamarin.Android Version (eg: 6.0):
Version: 7.0.2.37
### Operating System & Version (eg: Mac OSX 10.11):
Sierra
### Support Libraries Version (eg: 23.3.0):
24.2.1
### Describe your Issue:

Can't compile app after nugget updates

### Steps to Reproduce (with link to sample solution if possible):
update to latest nuggets go support libraries and Xamarin.facenook
### Include any relevant Exception Stack traces, build logs, adb logs:

	/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: error : Tool exited with code: 2. Output: 
trouble writing output: Too many field references: 70587; max is 65536.
You may try using --multi-dex option.
References by package:
     3 android.accounts
    30 android.app
     1 android.content
    36 android.content.pm
     9 android.content.res
     3 android.database
    48 android.graphics
     2 android.media
     1 android.media.browse
     2 android.net
     3 android.opengl
    19 android.os
     3 android.print
     1 android.provider
     8 android.runtime
  2708 android.support.compat
  2708 android.support.coreui
  2708 android.support.coreutils
  2782 android.support.customtabs
  2708 android.support.design
    58 android.support.design.internal
   679 android.support.design.widget
  2708 android.support.fragment
  2861 android.support.graphics.drawable
  2708 android.support.graphics.drawable.animated
  2708 android.support.mediacompat
  2708 android.support.v4
    13 android.support.v4.accessibilityservice
    17 android.support.v4.animation
   863 android.support.v4.app
   111 android.support.v4.content
     1 android.support.v4.content.pm
     1 android.support.v4.content.res
     9 android.support.v4.graphics
    41 android.support.v4.graphics.drawable
     4 android.support.v4.hardware.display
    12 android.support.v4.hardware.fingerprint
    10 android.support.v4.internal.view
   350 android.support.v4.media
   300 android.support.v4.media.session
     7 android.support.v4.net
    19 android.support.v4.os
    63 android.support.v4.print
     9 android.support.v4.provider
    55 android.support.v4.text
     6 android.support.v4.text.util
   102 android.support.v4.util
   433 android.support.v4.view
   137 android.support.v4.view.accessibility
     8 android.support.v4.view.animation
   495 android.support.v4.widget
   397 android.support.v7.app
  2708 android.support.v7.appcompat
  2708 android.support.v7.cardview
     8 android.support.v7.content.res
    18 android.support.v7.graphics.drawable
  2708 android.support.v7.recyclerview
     1 android.support.v7.text
     2 android.support.v7.transition
   124 android.support.v7.util
    77 android.support.v7.view
   248 android.support.v7.view.menu
  1398 android.support.v7.widget
    89 android.support.v7.widget.helper
     1 android.support.v7.widget.util
  2708 android.support.wearable
    22 android.support.wearable.activity
     2 android.support.wearable.companion
     8 android.support.wearable.input
     4 android.support.wearable.media
     5 android.support.wearable.provider
   542 android.support.wearable.view
   128 android.support.wearable.watchface
     7 android.text
     1 android.text.util
    14 android.util
    19 android.view
     8 android.view.accessibility
     1 android.view.inputmethod
    15 android.widget
   158 bolts
  2708 bolts.applinks
  3109 com.facebook
   159 com.facebook.appevents
    39 com.facebook.appevents.internal
    46 com.facebook.applinks
   550 com.facebook.internal
   174 com.facebook.login
    81 com.facebook.login.widget
    32 com.facebook.messenger
    51 com.facebook.share
   360 com.facebook.share.internal
   113 com.facebook.share.model
   124 com.facebook.share.widget
  2702 com.google.android.gms
    20 com.google.android.gms.actions
    13 com.google.android.gms.ads.identifier
    53 com.google.android.gms.auth
     7 com.google.android.gms.auth.api.credentials
    57 com.google.android.gms.auth.api.signin
    13 com.google.android.gms.auth.api.signin.internal
    75 com.google.android.gms.auth.firstparty.shared
  2702 com.google.android.gms.base
    38 com.google.android.gms.clearcut
    94 com.google.android.gms.common
    87 com.google.android.gms.common.api
   179 com.google.android.gms.common.api.internal
    42 com.google.android.gms.common.data
    49 com.google.android.gms.common.images
   171 com.google.android.gms.common.internal
     1 com.google.android.gms.common.internal.safeparcel
     4 com.google.android.gms.common.server
    12 com.google.android.gms.common.server.converter
    33 com.google.android.gms.common.server.response
    62 com.google.android.gms.common.stats
    27 com.google.android.gms.dynamic
     2 com.google.android.gms.dynamite.descriptors.com.google.android.gms.flags
    16 com.google.android.gms.flags.impl
  2805 com.google.android.gms.gcm
    47 com.google.android.gms.iid
   325 com.google.android.gms.internal
  2718 com.google.android.gms.measurement
   350 com.google.android.gms.measurement.internal
    32 com.google.android.gms.playlog.internal
     6 com.google.android.gms.security
    26 com.google.android.gms.signin.internal
   371 com.squareup.okhttp
    92 com.squareup.okhttp.internal
   246 com.squareup.okhttp.internal.framed
   134 com.squareup.okhttp.internal.http
    15 com.squareup.okhttp.internal.io
    16 com.squareup.okhttp.internal.tls
   347 com.squareup.picasso
     7 java.lang
     7 java.lang.annotation
     6 java.net
     1 java.nio
     6 java.util
     4 java.util.concurrent
     3 java.util.logging
    12 md5000ebe06cc2f48a20a556eeae0c3cc8a
     4 md50890773b370883bd2a9663699cac82d1
     2 md50adc1702d640cd02f710d8e07040fe7d
     2 md50d1192fa26e0ea90ab1f3e11360c3d59
     8 md51c2d49f89f3f016dbee9c4564847d236
     8 md51fabd57966a212ca82e7b20b5e5a4037
     8 md531f8cc8d4d39b2fa02686ee0eb368905
     6 md538aeae9bdd295ab387ed884128b5042a
     6 md53b54e9e4871bdc9f8c75aac983d44f39
     2 md555f960953c2d2771f58ed7e82f11629b
     4 md5613e4112eea159c70f91693ed7674968
     2 md58ca8ca9a1f8dc9075a0cb027f5be086b
   132 md594e289dcf9ae1d6f7104a9e79c37526c
     4 md59f70a99687498e7ba187118950981d26
    12 md5a104545e4d19c4ffe9ec3d5074a3b979
     6 md5a7dc5efaa3df19864db17f2d2f415d22
     2 md5b84297ba8e47a8e699fdff0f5b6b8bca
     2 md5d8b46a50680b342c7baa0696ed489930
     2 md5e6df0d51c0b26573e8336e434596095c
     6 mono
     4 mono.android.accessibilityservice
     2 mono.android.accounts
    12 mono.android.animation
    31 mono.android.app
     2 mono.android.bluetooth
    20 mono.android.content
     2 mono.android.database.sqlite
     6 mono.android.drm
     6 mono.android.gesture
     2 mono.android.graphics
     2 mono.android.graphics.drawable
     8 mono.android.hardware
     2 mono.android.hardware.display
     2 mono.android.hardware.input
     2 mono.android.inputmethodservice
     8 mono.android.location
    60 mono.android.media
    16 mono.android.media.audiofx
     2 mono.android.media.effect
     2 mono.android.media.midi
     2 mono.android.media.session
     2 mono.android.media.tv
     2 mono.android.net
     6 mono.android.net.nsd
     2 mono.android.net.sip
    18 mono.android.net.wifi.p2p
     2 mono.android.nfc
    10 mono.android.os
    10 mono.android.preference
     2 mono.android.renderscript
     6 mono.android.runtime
     6 mono.android.sax
     2 mono.android.speech
     4 mono.android.speech.tts
     8 mono.android.support.design.widget
     4 mono.android.support.v4.app
     4 mono.android.support.v4.content
     2 mono.android.support.v4.media.session
     2 mono.android.support.v4.os
    18 mono.android.support.v4.view
     4 mono.android.support.v4.view.accessibility
    12 mono.android.support.v4.widget
     6 mono.android.support.v7.app
    32 mono.android.support.v7.widget
    22 mono.android.support.wearable.view
     2 mono.android.text
     2 mono.android.transition
    72 mono.android.view
     4 mono.android.view.accessibility
     2 mono.android.view.animation
     2 mono.android.view.textservice
     8 mono.android.webkit
    72 mono.android.widget
     6 mono.com.facebook.internal
     2 mono.com.facebook.login.widget
     2 mono.com.facebook.share.widget
     2 mono.com.google.android.gms.common.api
     2 mono.com.google.android.gms.common.images
     2 mono.com.google.android.gms.security
     2 mono.com.squareup.picasso
     4 mono.java.lang
     2 mono.java.util
     2 mono.javax.xml.transform
   100 okio
     2 opentk
     2 opentk.platform.android
     2 opentk_1_0
     2 opentk_1_0.platform.android
     1 org.json
  2702 ... mypackagename

**Comment by martijn00** [comment]
So why don't you enable Multi-Dex as the output says?

**Comment by AlexanderOsokin** [comment]
Because of limitations described at this article: 
https://developer.android.com/studio/build/multidex.html

Not so good:
2708 android.support.compat
2708 android.support.coreui
2708 android.support.coreutils
2782 android.support.customtabs
2708 android.support.design
2708 android.support.fragment
2861 android.support.graphics.drawable
2708 android.support.graphics.drawable.animated
2708 android.support.mediacompat
2708 android.support.v4
2708 android.support.v7.appcompat
2708 android.support.v7.cardview
2708 android.support.v7.recyclerview
1398 android.support.v7.widget
2708 android.support.wearable
2708 bolts.applinks
3109 com.facebook

**Comment by martijn00** [comment]
Well, you need to remove some libraries, or accept the limitations. This is not a bug in any case.

**Comment by AlexanderOsokin** [comment]
I can't remove any library. Multi-Dex is not working with jdk 1.8.  

So,  ~40k references for Support.Design , Support.v4,  Support.v7 and ~6k for Xamarin.Facebook(and dependencies) is normal situation ?

**Comment by AlexanderOsokin** [comment]
https://bugzilla.xamarin.com/show_bug.cgi?id=44187

**Comment by kjeremy** [comment]
@AlexanderOsokin Drop the new proguard into your android sdk after enabling multidex and it will work.

**Comment by AlexanderOsokin** [comment]
@kjeremy Thank you
