### ISSUE TITLE
Update bindings to 25.2.0

### ISSUE THREAD

**Issue by luconlua** [xamarin/AndroidSupportComponents#40]
https://developer.android.com/topic/libraries/support-library/revisions.html#25-2-0

**Comment by Redth** [comment]
Working on it :) https://github.com/xamarin/AndroidSupportComponents/tree/v25.2.0

**Comment by luconlua** [comment]
Can we have a beta version soon? 
I need the fix for this annoying bug in the support library:
https://code.google.com/p/android/issues/detail?id=230171

**Comment by Redth** [comment]
Beta version is out on nuget `25.2.0-beta1`

**Comment by Redth** [comment]
PR: https://github.com/xamarin/AndroidSupportComponents/pull/42

**Comment by luconlua** [comment]
wow - Thx!

**Comment by borgdylan** [comment]
@Redth documentation I read from google also suggests that the constraint layout library has a new release in beta mode (as opposed to the alpha0 release).

**Comment by Redth** [comment]
You're correct.  It's on my todo list, but not sure I'll get to it for a bit, I'm off on vacation for a couple weeks now... We'll see how much time I get to open the laptop during it.

**Comment by modplug** [comment]
🥇 @Redth Here is some well deserved motivation for the constraint layout update :)

**Comment by Redth** [comment]
We are going to skip a stable release of 25.2.0 in favour of releasing 25.3.1.
