### ISSUE TITLE
Update bindings to v25.3.1

### ISSUE THREAD

**Issue by martijn00** [xamarin/AndroidSupportComponents#43]
https://developer.android.com/topic/libraries/support-library/revisions.html#25-3-0

**Comment by Redth** [comment]
25.3.1-beta1 has been released to nuget.

We are undergoing QA testing now before a stable release.

**Comment by kjeremy** [comment]
It's been 3 weeks.  Can we get this on stable yet?

**Comment by Redth** [comment]
Complete!
