### ISSUE TITLE
Error inflating class android.support.design.widget.NavigationView

### ISSUE THREAD

**Issue by vhugogarcia** [xamarin/AndroidSupportComponents#44]
### Xamarin.Android Version (eg: 6.0):
Xamarin.Android
Version: 7.1.0.2 

### Operating System & Version (eg: Mac OSX 10.11):
Mac OS 10.12.3

### Support Libraries Version (eg: 23.3.0):
25.1.1

### Describe your Issue:
When using AppCompat theme I'm getting an error: 
Binary XML file line #1: Binary XML file line #1: Error inflating class android.support.design.widget.NavigationView

### Steps to Reproduce (with link to sample solution if possible):
http://pastebin.com/ivxN3hLW

### Include any relevant Exception Stack traces, build logs, adb logs:
The inner exception message is: "You need to use a Theme.AppCompat theme (or descendant) with the design library."

**Comment by Redth** [comment]
Looks like you aren't actually _using_ the theme in your activity.

You might want to add `Theme="@style/AppTheme"` to your `[Activity (...)]` attribute.

**Comment by Redth** [comment]
Ahh i just noticed the last comment in your paste... It should in theory work to set the theme globally.  What happens if you simply use `@style/Theme.AppCompat` instead of your derived theme?

**Comment by Redth** [comment]
Closing until more info is provided.
