### ISSUE TITLE
Update bindings for v26.0

### ISSUE THREAD

**Issue by martijn00** [xamarin/AndroidSupportComponents#46]
https://developer.android.com/topic/libraries/support-library/revisions.html#26-0-1

**Comment by martijn00** [comment]
v26 has gone into stable now. Is it possible to get this released so we can update our apps to use with Android O?

**Comment by jamesmontemagno** [comment]
I think we need build support for 26 first in Xamarin.Android to get v26

**Comment by csdinon** [comment]
When build support for 26 does comes out we will **need** the support bindings specifically for https://developer.android.com/guide/topics/ui/notifiers/notifications.html#ManageChannels

**Comment by furiousbuilder** [comment]
Any news for V26?

**Comment by tipa** [comment]
Any updates?

**Comment by furiousbuilder** [comment]
There is a 26rc1 version on nuget :)
