### ISSUE TITLE
Xamarin.Android.Support.v4 App.ActivityOptionsCompat.ToBundle() always returns null

### ISSUE THREAD

**Issue by kjeremy** [xamarin/AndroidSupportComponents#47]
See https://bugzilla.xamarin.com/show_bug.cgi?id=51180

**Comment by Redth** [comment]
Thanks.  I believe this is very similar to https://bugzilla.xamarin.com/show_bug.cgi?id=40527

Basically the `ActivityOptionsImpl23` class is bound and it shouldn't be...

Investigating...

**Comment by Redth** [comment]
Please try v25.3.1-beta1, I can't reproduce the issue with this version any longer.
