### ISSUE TITLE
IntelliSense missing for Android layout files when adding Xamarin.Android.Support.Design

### ISSUE THREAD

**Issue by strombringer** [xamarin/AndroidSupportComponents#52]
### Xamarin.Android Version (eg: 6.0):
7.1

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10, Visual Studio 2017

### Support Libraries Version (eg: 23.3.0):
25.1.1

### Describe your Issue:
IntelliSense is missing for Android layout files when adding the Xamarin.Android.Support.Design package.
When I use widgets from the android.support.design namespace in my layout, the generated xml schema in "...\obj\Debug\Schemas\25\schemas.android.com.apk.res.auto.xsd" contains duplicate attributes for "itemIconTint" and "itemTextColor"

The error message is only barely visible as a small blue squiggly underline at the beginning of the last line in the layout file:
![error_message](https://cloud.githubusercontent.com/assets/3511229/24709846/90cb0990-1a1b-11e7-8fec-2c7f4baa1ff8.png)

Excerpt from the xsd file with the duplicate attributes:
![attributes](https://cloud.githubusercontent.com/assets/3511229/24709850/93c088f0-1a1b-11e7-8502-4f460bb1c779.png)

In addition: After removing the design widgets the error remains, even after deleting the obj folder, "Clean Solution" and Visual Studio restart. The xsd file is generated with the duplicate attributes as soon as a layout file is opened, even if it doesn't contain the res-auto namespace declaration or android.support.design widgets.

### Steps to Reproduce (with link to sample solution if possible):
1. Create Blank Android Project
2. Install-Package Xamarin.Android.Support.v7.AppCompat
3. Open Resource\layout\Main.axml -> "...\obj\Debug\Schemas\25\schemas.android.com.apk.res.auto.xsd" is generated without duplicates (ca. 768 KB) (IntelliSense is still working)
4. Install-Package Xamarin.Android.Support.Design
5. Open Resource\layout\Main.axml -> "...\obj\Debug\Schemas\25\schemas.android.com.apk.res.auto.xsd" is generated **with** duplicates (ca. 1717 KB) (IntelliSense is no longer working)

**Comment by Redth** [comment]
@garuma any ideas/input you can provide?

**Comment by garuma** [comment]
@Redth @decriptor can chime in on that

**Comment by decriptor** [comment]
@Redth I'm pretty sure I know what is going on here. I've fixed this for another case somewhere else, but it looks like I'll need to add a better fix to catch other cases of this.

**Comment by decriptor** [comment]
Ok, I've tracked this down and fixed the issue.

**Comment by Splinterjke** [comment]
IntelliSense is still not working with Support.Design and v7.AppCompat installed.

**Comment by decriptor** [comment]
There hasn't been an update with the fix in it yet.

**Comment by decriptor** [comment]
I just checked and the code is definitely in for the next release. It should be available in the next preview

**Comment by kamikyo** [comment]
I have the same problem.
windows 10
visual studio 15.7.4
xamarin.android 8.3.3.3
api level 26
![image](https://user-images.githubusercontent.com/7645337/42429533-fd781a78-836b-11e8-9279-a8752d1bf365.png)
