### ISSUE TITLE
RemovePage in Navigation crash

### ISSUE THREAD

**Issue by kostadinSpiridonov** [xamarin/AndroidSupportComponents#53]
### Describe your Issue:
After upgrading the various Xamarin.Android.XXXX packages from 23.3.0 to 25.3.1 with NuGet, an app will crash when using Page.Navigation.RemovePage (for example to remove the page below the top page on the stack) and then Page.Navigation.AsyncPop().

### Steps to Reproduce (with link to sample solution if possible):
1. Add three pages in navigation stasck
2. Remove one of them with RemovePage method
3. Call PopAsync method

### Expected Results
You will be returned to page 1

### Actual Results
The app crashes

**Comment by Ralle1986** [comment]
I also have the same problem

**Comment by jamesmontemagno** [comment]
You would want to support this on the Xamarin.Forms bugzilla as it doesn't pertain to the support libraries.
