### ISSUE TITLE
Strong name signing for Android.Support assemblies

### ISSUE THREAD

**Issue by callanh** [xamarin/AndroidSupportComponents#54]
Hi!

Can you please sign your assemblies in the next update to the nuget packages?

    Referenced assembly 'Xamarin.Android.Support.Core.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

    Referenced assembly 'Xamarin.Android.Support.Design, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

We use strong name signing for our projects and it is a bit of a cascading requirement.  In the meantime, I will use the strong name signer tool (https://brutaldev.com/post/net-assembly-strong-name-signer) to workaround the issue.

Thanks
Callan.

**Comment by Redth** [comment]
We've debated this in the past and actually got close to implementing it, but we found scenarios where it causes breaking changes to existing libraries and customers which we decided was unacceptable.  We may revisit this in the future, but for now we will not be implementing it.

**Comment by callanh** [comment]
Thanks for the response. Out of curiosity, what were the breaking changes to existing libraries?

Strong-naming is a total mess. You need strong naming to install to the GAC using ngen (can significantly improve cold-start times of large apps).  If you want to be a 'friend' assembly to a strong-named assembly, you must be strong-named yourself. To be able to replace a leaf DLL in a production system, you need strong-named assemblies.  If you want to be strong-named, all your references must be strong-named as well.

**Comment by Redth** [comment]
Basically, if another library referenced a non-strong named version of a support library and your application referenced the strong named version it would cause issues.  So, strong naming our assemblies would require all other library authors to also reference the strong named version.  We had also considered releasing strong named versions of the same packages, but there's already enough packages for android support to confuse.  Ultimately, strong naming is not super common in Xamarin apps (I'm curious what is forcing the strong naming requirement on your project) and given solutions exist to work around the issue (like you mentioned), it simply wasn't the right move for us to do at the time.

**Comment by callanh** [comment]
We are writing large cross-platform apps (WPF, UWP, Android, iOS).  The dependency hell starts with running ngen.exe on our WPF app to improve the cold-start. The WPF app (strong-named for ngen) references a shared PCL library (so has to be strong-named). That PCL is necessarily a 'friend' to an Android library (so has to be strong-named as well).  Our Android library references the Xamarin Android support library (which is not strong-named), so we have to use the StrongNameSigner and then commit the fixed DLL to source control.
