### ISSUE TITLE
Project resources are missing in Resources window and axml intellisence after adding (Xamarin.Android.Support.V7.AppCompat)

### ISSUE THREAD

**Issue by jawad-younes** [xamarin/AndroidSupportComponents#55]
### Xamarin.Android Version (eg: 6.0):
7.3.0.13

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10, Visual Studio 2015 Update 3

### Support Libraries Version (eg: 23.3.0):
25.3.1 (And some older versions)

### Describe your Issue:
Project resources are missing in (Resources Window -> Project Resoures Tab) and in axml intellisence, after installing (Support.V7.AppCompat) from NuGet.

### Steps to Reproduce (with link to sample solution if possible):

1. Create Blank Android Project
2. Open Resource\layout\Main.axml
3. Add ImageView and try to change the (src) property from Properties window. The resources window has drawable resource called (icon). OK (Figure 1)
![2017-05-25_15-48-13](https://cloud.githubusercontent.com/assets/28406316/26452203/c843a09e-4167-11e7-854e-3a145d59550c.png)
4. Install package (Xamarin.Android.Support.v7.AppCompat) (and all its dependencies) from NuGet.
5. Restart VS (This is another issue that I have to restart to be able to recompile after installing some libraries from NuGet !)
6. Clean the project (From Build menu), and rebuild the project.
7. Open Resource\layout\Main.axml again and try to set the (src) property of the ImageView. The resources window now has multiple project resources (from support library) but not the resources that are in the project ! (Figure 2)
![2017-05-25_15-56-39](https://cloud.githubusercontent.com/assets/28406316/26452212/d22cd5a8-4167-11e7-9bfc-aa89a3550555.png)
8. These resources are missing now in axml intellisence when trying to set the (src) property of the ImageView in xml file.
9. If I uninstall (Support.V7.AppCompat) and leave its dependencies, the resources come back again in the resources list is Resources window and axml intellisence.

**Comment by Redth** [comment]
@garuma any ideas on this one?

**Comment by garuma** [comment]
Hey @jawad-younes, can you confirm once you rebuild your project after adding the support package that your icon is indeed present in the `obj/Debug/res` folder of your app?

Thanks.

**Comment by jawad-younes** [comment]
@garuma,
Yes, all resources are copied to obj/Debug/res, and the program is working fine on device and emulator.

The problem is in intellisence in .axml file and in the Resources window.

The intellisence of project resources in code is working fine.

**Comment by garuma** [comment]
Is your icon stored under a `drawable` folder or a `mipmap` folder?

**Comment by jawad-younes** [comment]
All images are stored in drawable folder. (But the sample above, has only one image, the Icon).

The problem is not in this icon only, but in all resources even strings; They don't appear in .axml intellisence or in Resources window, so I have to write them manually witch is not a big problem, but still not perfect !;

But they DO appear in c# code, i.e. the Resource Class's members are generated successfully.

**Comment by Redth** [comment]
Going to close this as Xamarin.Android in release 15.6 has a resource system that's been rewritten in managed C# which _should_ make this a non-issue.  If it's still happening, please open a new issue with a reproducible sample. Thanks!
