### ISSUE TITLE
ChainStyle not be used at ConstraintLayout

### ISSUE THREAD

**Issue by yuka1984** [xamarin/AndroidSupportComponents#60]
Xamarin 4.5.0.486
Xamarin.Android 7.3.1.2
Windows 10

Support Libraries 25.3.1
and Xamarin.Android.Support.Constraint.Layout 1.0.2

### Describe your Issue:
Xamarin.Android.Support.Constraint.Layout app:layout_constraintVertical_chainStyle not be used as ConstraintLayout.

### Include any relevant Exception Stack traces, build logs, adb logs:
No resource identifier found for attribute 'layout_constraintVertical_chainStyle' in package .

**Comment by csdinon** [comment]
I'm seeing this for all attributes added after alpha9. Not just ChainStyle. You can reference all the apis programmatically, but you get a `Java.Lang.NoSuchFieldError`

It appears the [AssemblyInfo.cs](https://github.com/xamarin/AndroidSupportComponents/blob/master/constraint-layout/source/Properties/AssemblyInfo.cs) is still referencing alpha9?

Same thing for [AssemblyInfo.cs](https://github.com/xamarin/AndroidSupportComponents/blob/master/constraint-layout-solver/source/Properties/AssemblyInfo.cs) in the solver

**Comment by Redth** [comment]
Sorry folks, going to publish a fix shortly.

**Comment by Redth** [comment]
Try v1.0.2.1 of the nuget packages.

**Comment by yuka1984** [comment]
I confirmed that the ChainStyle can be used. Thx.

**Comment by csdinon** [comment]
👍 thanks for the quick fix
