### ISSUE TITLE
Internal classes are public and may actually be useful.

### ISSUE THREAD

**Issue by Redth** [xamarin/AndroidSupportComponents#63]
Google for some reason marks classes inside of `internal` packages as public, and sometimes they are useful.

In this case `BottomNavigationItemView` and `BottomNavigationMenuView` are some culprits:

Related to comments on #62 from @corjohnson
Some additional info: https://stackoverflow.com/questions/36032177/android-new-bottom-navigation-bar/36033640#36033640 and https://stackoverflow.com/questions/41649494/how-to-remove-icon-animation-for-bottom-navigation-view-in-android/41690461

**Comment by jamesmontemagno** [comment]
These were available in 25.3.1, but now missing from 25.4.X :(

**Comment by kanvuduc** [comment]
@Redth I made the fixes for these bugs. Could I make a pull request?

**Comment by Redth** [comment]
Fixed in 25.4.0.2
