### ISSUE TITLE
TextInputEditText  missing

### ISSUE THREAD

**Issue by ravigajadin** [xamarin/AndroidSupportComponents#64]
Support Libraries Version: Xamarin.Android.Support.Design 25.4.0.1

Describe your Issue:

Assembly Xamarin.Android.Support.Design is missing the TextInputEditText class. Had to rollback to 25.3.1 to use the class.

**Comment by kanvuduc** [comment]
@Redth I made the fix for this one. Could I make a pull request?

**Comment by Redth** [comment]
@kanvuduc definitely appreciate the offer, but master is tracking with fixes for this right now already.

**Comment by kanvuduc** [comment]
Just created a pull request. Hope it will help.

**Comment by Redth** [comment]
This should be fixed in 25.4.0.2
