### ISSUE TITLE
TextInputEditText missing

### ISSUE THREAD

**Issue by softlion** [xamarin/AndroidSupportComponents#67]
package id="Xamarin.Android.Support.Design" version="25.4.0.1" targetFramework="monoandroid71"

### Xamarin.Android Version (eg: 6.0):
7.4.0.21

### Operating System & Version (eg: Mac OSX 10.11):
Win10

### Support Libraries Version (eg: 23.3.0):
25.4.0.1

### Describe your Issue:
TextInputEditText class is missing. Was there in v25.3

### Include any relevant Exception Stack traces, build logs, adb logs:

https://developer.android.com/reference/android/support/design/widget/TextInputEditText.html

**Comment by martijn00** [comment]
Did you try 25.4.0.2?
