### ISSUE TITLE
Listview Refreshindicator disappears direct on Android after upgrade

### ISSUE THREAD

**Issue by michelmoorlag** [xamarin/AndroidSupportComponents#68]
### Xamarin.Android Version (eg: 6.0):
6.0

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10

### Support Libraries Version (eg: 23.3.0):
24.2.1 and higher

### Describe your Issue:
I am using a XF listview and want to disable pull to refresh while loading. I am binding the listview IsPullToRefreshEnabled to the oposite of the IsRefreshing property. When I pull to refresh I see the listview refresh icon turning until the new data is shown.  I am using binding and retreive my data async.
This all worked fine up to version 23.4.0.1 of the android support libs. When I upgrade to version 24.2.1 or higher and I pull to refresh I do see the refesh icon for a short moment and then it disseapers before the new data is retreived and shown.

### Steps to Reproduce (with link to sample solution if possible):
See the small and simple sample application I added. It will show the bug discribed. When you donwgrade the support libs to version 23.4.0.1 OR remove the binding on IsPullToRefreshEnabled and set it to True it will work like expected. 

[RefreshIndicator.zip](https://github.com/xamarin/AndroidSupportComponents/files/1270125/RefreshIndicator.zip)

### Include any relevant Exception Stack traces, build logs, adb logs:
-

**Comment by Redth** [comment]
Could you please file this in Xamarin.Forms along with the repro sample?  I'm seeing it here too but unfortunately this looks related to Xamarin.Forms and not directly to Android Support Libraries.  It's also possible it's solved in newer releases of Xamarin.Forms.

https://github.com/xamarin/Xamarin.Forms/issues
