### ISSUE TITLE
add samsung custom tab "com.sec.android.app.sbrowser"

### ISSUE THREAD

**Issue by i-omar** [xamarin/AndroidSupportComponents#69]
### Describe your Issue:
can you add support to samsung custom tab

**Comment by Redth** [comment]
We just bind the libraries google provides.  

I haven't looked into this extensively, but I believe you can add support by utilizing custom tabs in a certain way.

Here's a java demo using Samsung's custom tabs https://github.com/SamsungInternet/examples/tree/master/custom-tab-demo

Shouldn't be too difficult to do the same in C#
