### ISSUE TITLE
Exception when ConstraintLayout is added

### ISSUE THREAD

**Issue by AlmondMedia** [xamarin/AndroidSupportComponents#70]
After adding the constraint layout package via nugget package manager,

I tried to use it and got the following:

![screen shot 2017-09-27 at 12 57 37](https://user-images.githubusercontent.com/18498330/30912354-1266239e-a384-11e7-88b6-6118ecefd0fa.jpg)
![screen shot 2017-09-27 at 13 00 15](https://user-images.githubusercontent.com/18498330/30912361-1653bba6-a384-11e7-8f46-16afa17531d9.jpg)
![screen shot 2017-09-27 at 13 00 59](https://user-images.githubusercontent.com/18498330/30912365-193fe790-a384-11e7-8edb-40b975ae16de.jpg)

**Comment by johnjake** [comment]
does barrierDirection works on your constrain layout?

**Comment by Redth** [comment]
Not able to reproduce this in the latest stable Xamarin.Android with Xamarin.Android.Support.Constraint.Layout 1.0.2.2.  I suspect this might have been related to previous versions of this nuget package not bundling the java libraries in a way that the designer was expecting, which has now been fixed.
