### ISSUE TITLE
Xamarin.Android.* libs in 26.0.2-beta1 causing XF app build failure - error APT0000

### ISSUE THREAD

**Issue by Szymaniuk** [xamarin/AndroidSupportComponents#71]
### Xamarin.Android Version (eg: 6.0):
Xamarin.Forms 2.4.0.280

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10 Pro 64-bit (1703 - 15063.608)

### Support Libraries Version (eg: 23.3.0):
26.0.2-beta1

### Describe your Issue:
I used Xamarin.Forms 2.4.0.280 + Xamarin.Android.*** support libraries in version 25.4.0.2 - everything works fine. Today I decided to try newest beta release of Xamarin.Android.*** support libraries, so I've updated them to 26.0.2-beta1.
After that, my project building starts crashing with below error:
`error APT0000:  Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.`

### Steps to Reproduce (with link to sample solution if possible):
Update XF app, that uses Xamarin.Android libaries in 25.4.0.2, to 26.0.2-beta1.

### Include any relevant Exception Stack traces, build logs, adb logs:
```
6>C:\workspace\MyApp.Mobile\MyApp\MyApp.Android\obj\Debug\__library_projects__\Xamarin.Android.Support.v7.AppCompat\library_project_imports\res\values-v26\values-v26.xml(2): error APT0000:  Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
6>C:\workspace\MyApp.Mobile\MyApp\MyApp.Android\obj\Debug\__library_projects__\Xamarin.Android.Support.Design\library_project_imports\res\values-v26\values-v26.xml(2): error APT0000:  Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
```

**Comment by Redth** [comment]
You need to use our latest alpha/beta channel releases and set your app to compile against Android Oreo (API 26).

Keep in mind your android support library _major_ version number should match your app's compile sdk version number.
