### ISSUE TITLE
BottomNavigationView item titles set in .cs are lost upon navigation

### ISSUE THREAD

**Issue by lirkki** [xamarin/AndroidSupportComponents#73]
### Xamarin.Android Version: 
8.1.0.20
### Operating System & Version: 
Mac OSX 10.13
### Support Libraries Version (eg: 23.3.0): 
26.0.2
### Describe your Issue:
I am setting BottomNavigationView item titles in my Activity OnCreate method in .cs file. The titles are shown correctly upon the first time the BottomNavigationView is shown. When I select any other item, the titles set in .cs file are not respected anymore but the titles in layout xml are applied from then on.

The titles set in code behind must be the ones to use once they've been set in .cs code behind file. Otherwise BottomNavigationView cannot use any localization mechanism that relies on setting the text in .cs file.

### Steps to Reproduce (with link to sample solution if possible):

1. Start the application in attached sample solution. The titles in bottom navigation are "1_cs" and "2_cs" which have been set in .cs code behind file.
1. Choose the "2_cs" item in bottom navigation.

Expected result: The titles in bottom navigation are unchanged i.e. they are still "1_cs" and "2_cs".

Actual result: The titles change to "1_xml" and "2_xml". 

### Include any relevant Exception Stack traces, build logs, adb logs:

Sample project for reproducing the issue: 
[BottomNavigationView_title_codebehind.zip](https://github.com/xamarin/AndroidSupportComponents/files/1405896/BottomNavigationView_title_codebehind.zip)

**Comment by Redth** [comment]
Same thing happens in a java project, so unfortunately this is not a binding issue, it's an issue with google's library itself.  However, the BottomNavigationItemView.setTitle is restricted in scope to LIBRARY_GROUP only, which means you're really not supposed to call it yourself directly.

Try setting it via the menu instead.  This works fine for me:

```
bottomNavigation.Menu.GetItem(0).SetTitle("1_cs");
bottomNavigation.Menu.GetItem(1).SetTitle("2_cs");
```
