### ISSUE TITLE
I having problems to show a custom screen from Microsoft.Identity.Client using CustomTabs

### ISSUE THREAD

**Issue by jeer65** [xamarin/AndroidSupportComponents#81]
### Describe your Issue:
An application to connect to Azure using AD to B2C authentication, is using the  Microsoft.Identity.Client, and the version that is working is Custom Tabs 23.3, but when I tried to install through Nudget Microsoft.Identity.Client, this installs version Custom Tabs 26.x.
And when I run the code, it throws  the following error,

12-06 02:09:42.177 D/ViewRootImpl@ec13238[MainActivity]( 6553): MSG_WINDOW_FOCUS_CHANGED 0
12-06 02:09:42.181 D/InputMethodManager( 6553): HSI from window - flag : 0 Pid : 6553
12-06 02:09:42.225 V/ActivityThread( 6553): performLaunchActivity: mActivityCurrentConfig={0 1.0 themeSeq = 0 showBtnBg = 0 311mcc480mnc [en_US] ldltr sw360dp w360dp h668dp 480dpi nrml long port ?dc finger -keyb/v/h -nav/h mkbd/h desktop/d s.53}
12-06 02:09:42.251 D/Mono    ( 6553): Assembly Ref addref Microsoft.Identity.Client[0xdcdc2e80] -> Xamarin.Android.Support.CustomTabs[0xdc48d560]: 2
12-06 02:09:42.270 D/Mono    ( 6553): DllImport searching in: '__Internal' ('(null)').
12-06 02:09:42.270 D/Mono    ( 6553): Searching for 'java_interop_jnienv_get_object_field'.
12-06 02:09:42.270 D/Mono    ( 6553): Probing 'java_interop_jnienv_get_object_field'.
12-06 02:09:42.270 D/Mono    ( 6553): Found as 'java_interop_jnienv_get_object_field'.
An unhandled exception occured.
### Steps to Reproduce (with link to sample solution if possible):

Run this code 
AuthenticationResult ar = await App.PCA.AcquireTokenAsync(App.Scopes, GetUserByPolicy(App.PCA.Users, App.PolicySignUpSignIn), App.UiParent);

**Comment by Redth** [comment]
Do you have a reproducible solution you could share as well as more context around the logs (perhaps the full adb logcat output could help)?  Also, have you tried contacting the owners of Microsoft.Identity.Client? Sounds like it could be an issue with their library's compatibility.

**Comment by newky2k** [comment]
No response since dec 2017
