### ISSUE TITLE
`No resource found that matches the given name` when referring to an ID defined later in an XML file

### ISSUE THREAD

**Issue by cyberjacob** [xamarin/AndroidSupportComponents#84]
### Xamarin.Android Version (eg: 6.0):
8.1

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10

### Describe your Issue:
When referencing an ID in an XML file (such as a layout), the error `No resource found that matches the given name` is generated if the ID is defined later in the file. For example, a ConstraintLayout child which chains with another child. Android can deal with the later definition, so Xamarin should be able to as well.

### Steps to Reproduce (with link to sample solution if possible):
Example layout xml:

```xml
<android.support.constraint.ConstraintLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
    <Button
            android:id="@+id/one"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintEnd_toStartOf="@id/two"/>
    <Button
            android:id="@+id/two"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:layout_constraintStart_toEndOf="@id/one"
            app:layout_constraintEnd_toEndOf="parent"/>
</android.support.constraint.ConstraintLayout>
```

The line `app:layout_constraintEnd_toStartOf="@id/two"` will generate the error, as `@id/two` is not defined yet.

**Comment by FarizF** [comment]
Is there a way to get around this? I have this problem as well.

**Comment by cyberjacob** [comment]
@FarizF Make the first usage of the id `@+id/x`, regardless of if it's the actual object being referred to as the ID. That should work temporarily.

**Comment by erikpowa** [comment]
Same with fonts

```
<?xml version="1.0" encoding="utf-8"?>
<font-family xmlns:android="http://schemas.android.com/apk/res/android"
             xmlns:app="http://schemas.android.com/apk/res-auto">
    <font android:font="@font/Montserrat_Light"
          android:fontStyle="normal"
          android:fontWeight="300"
          app:font="@font/Montserrat_Light"
          app:fontStyle="normal"
          app:fontWeight="300" />
</font-family>
```
```
2>Resources\font\Montserrat.xml(2,0): Error APT0000: No resource found that matches the given name (at 'font' with value '@font/Montserrat_Light').
2>Resources\font\Montserrat.xml(2,0): Error APT0000: No resource found that matches the given name (at 'font' with value '@font/Montserrat_Light').
```

**Comment by newky2k** [comment]
Seems to have a work around

**Comment by zlannin** [comment]
I'm having the same issue, but the above solution won't work in my scenario.

    <android.support.constraint.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <Button
            android:id="@+id/keyboard_1"
            android:layout_width="0dp"
            android:layout_height="0dp"
            app:layout_constraintDimensionRatio="1:1"
            app:layout_constraintWidth_min="48dp"
            app:layout_constraintHeight_min="48dp"
            app:layout_constraintWidth_max="150dp"
            app:layout_constraintHeight_max="150dp"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintEnd_toStartOf="@id/keyboard_2"
            app:layout_constraintBottom_toTopOf="@id/keyboard_4"
            app:layout_constraintHorizontal_chainStyle="packed"
            app:layout_constraintVertical_chainStyle="packed"
            android:text="1" />

        <Button
            android:id="@+id/keyboard_2"
            android:layout_width="0dp"
            android:layout_height="0dp"
            app:layout_constraintDimensionRatio="1:1"
            app:layout_constraintWidth_min="48dp"
            app:layout_constraintHeight_min="48dp"
            app:layout_constraintWidth_max="150dp"
            app:layout_constraintHeight_max="150dp"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintStart_toEndOf="@id/keyboard_1"
            app:layout_constraintEnd_toStartOf="@id/keyboard_3"
            app:layout_constraintBottom_toTopOf="@id/keyboard_5"
            app:layout_constraintVertical_chainStyle="packed"
            android:text="2" />

        <Button
            android:id="@+id/keyboard_3"
            android:layout_width="0dp"
            android:layout_height="0dp"
            app:layout_constraintDimensionRatio="1:1"
            app:layout_constraintWidth_min="48dp"
            app:layout_constraintHeight_min="48dp"
            app:layout_constraintWidth_max="150dp"
            app:layout_constraintHeight_max="150dp"
            app:layout_constraintStart_toEndOf="@id/keyboard_2"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintBottom_toTopOf="@id/keyboard_6"
            app:layout_constraintVertical_chainStyle="packed"
            android:text="3" />

        <Button
            android:id="@+id/keyboard_4"
            android:layout_width="0dp"
            android:layout_height="0dp"
            app:layout_constraintDimensionRatio="1:1"
            app:layout_constraintWidth_min="48dp"
            app:layout_constraintHeight_min="48dp"
            app:layout_constraintWidth_max="150dp"
            app:layout_constraintHeight_max="150dp"
            app:layout_constraintTop_toBottomOf="@id/keyboard_1"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintEnd_toStartOf="@id/keyboard_5"
            app:layout_constraintBottom_toTopOf="@id/keyboard_7"
            app:layout_constraintHorizontal_chainStyle="packed"
            android:text="4" />

        <Button
            android:id="@+id/keyboard_5"
            android:layout_width="0dp"
            android:layout_height="0dp"
            app:layout_constraintDimensionRatio="1:1"
            app:layout_constraintWidth_min="48dp"
            app:layout_constraintHeight_min="48dp"
            app:layout_constraintWidth_max="150dp"
            app:layout_constraintHeight_max="150dp"
            app:layout_constraintTop_toBottomOf="@id/keyboard_2"
            app:layout_constraintStart_toEndOf="@id/keyboard_4"
            app:layout_constraintEnd_toStartOf="@id/keyboard_6"
            app:layout_constraintBottom_toTopOf="@id/keyboard_8"
            android:text="5" />

        <Button
            android:id="@+id/keyboard_6"
            android:layout_width="0dp"
            android:layout_height="0dp"
            app:layout_constraintDimensionRatio="1:1"
            app:layout_constraintWidth_min="48dp"
            app:layout_constraintHeight_min="48dp"
            app:layout_constraintWidth_max="150dp"
            app:layout_constraintHeight_max="150dp"
            app:layout_constraintStart_toEndOf="@id/keyboard_5"
            app:layout_constraintTop_toBottomOf="@id/keyboard_3"
            app:layout_constraintBottom_toTopOf="@id/keyboard_9"
            app:layout_constraintEnd_toEndOf="parent"
            android:text="6" />

        <Button
            android:id="@+id/keyboard_7"
            android:layout_width="0dp"
            android:layout_height="0dp"
            app:layout_constraintDimensionRatio="1:1"
            app:layout_constraintWidth_min="48dp"
            app:layout_constraintHeight_min="48dp"
            app:layout_constraintWidth_max="150dp"
            app:layout_constraintHeight_max="150dp"
            app:layout_constraintTop_toBottomOf="@id/keyboard_4"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintEnd_toStartOf="@id/keyboard_8"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintHorizontal_chainStyle="packed"
            android:text="7" />

        <Button
            android:id="@+id/keyboard_8"
            android:layout_width="0dp"
            android:layout_height="0dp"
            app:layout_constraintDimensionRatio="1:1"
            app:layout_constraintWidth_min="48dp"
            app:layout_constraintHeight_min="48dp"
            app:layout_constraintWidth_max="150dp"
            app:layout_constraintHeight_max="150dp"
            app:layout_constraintTop_toBottomOf="@id/keyboard_5"
            app:layout_constraintStart_toEndOf="@id/keyboard_7"
            app:layout_constraintEnd_toStartOf="@id/keyboard_9"
            app:layout_constraintBottom_toBottomOf="parent"
            android:text="8" />

        <Button
            android:id="@+id/keyboard_9"
            android:layout_width="0dp"
            android:layout_height="0dp"
            app:layout_constraintDimensionRatio="1:1"
            app:layout_constraintWidth_min="48dp"
            app:layout_constraintHeight_min="48dp"
            app:layout_constraintWidth_max="150dp"
            app:layout_constraintHeight_max="150dp"
            app:layout_constraintStart_toEndOf="@id/keyboard_8"
            app:layout_constraintTop_toBottomOf="@id/keyboard_6"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintBottom_toBottomOf="parent"
            android:text="9" />

    </android.support.constraint.ConstraintLayout>

**Comment by cyberjacob** [comment]
@zlannin What isn't working? You don't appear to have applied the workaround I suggested in that XML.

**Comment by zlannin** [comment]
@cyberjacob I misinterpreted your solution! Once I added `@+id/{id}` as you suggested to my constraint attributes everything worked 👍

**Comment by grasdy** [comment]
I have the same problem, but I can't move {@+id} before usage, because I use third-party aar with layouts. Is there any another case for fix this problem?

**Comment by Arcires** [comment]
@cyberjacob I've been trying multiple different suggestions for fixes to work around this issue, for the past 3 hours. You're a saint!

**Comment by gopalawasthi123** [comment]
Same issue with me
`<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/parentlayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

  <ImageView
    android:id="@+id/imageView"
    android:layout_width="80dp"
    android:layout_height="80dp"
    android:src="@drawable/facebook"
    android:layout_constraintLeft_toLeftOf="parent"
    android:layout_constraintTop_toTopOf="parent"/>

  <TextView
    android:layout_width="wrap_content"
    android_layout_height="wrap_content"
    android:text="Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum"
    android:layout_constraintLeft_toRightOf="@+id/imageView"
    android:layout_constraintRight_toRightOf="parent"/>
      
</android.support.constraint.ConstraintLayout>`

**Comment by cyberjacob** [comment]
@gopalawasthi123 What element is it complaining about?

**Comment by gopalawasthi123** [comment]
@cyberjacob  it gave me a compile time error that no resource found

**Comment by gopalawasthi123** [comment]
the exact error is: 
No resource identifier found for attribute 'layout_constraintLeft_toLeftOf' in package 'ellipsizetest.ellipsizetest'

**Comment by zlannin** [comment]
@gopalawasthi123 can you post the xml file you are talking about, your example above doesn't show the attribute `layout_constraintLeft_toLeftOf`.

**Comment by gopalawasthi123** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/parentlayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

  <ImageView
    android:id="@+id/imageView"
    android:layout_width="80dp"
    android:layout_height="80dp"
    android:src="@drawable/facebook"
    android:layout_constraintLeft_toLeftOf="parent"
    android:layout_constraintTop_toTopOf="parent"/>

  <TextView
    android:layout_width="wrap_content"
    android_layout_height="wrap_content"
    android:text="Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a"
    android:layout_constraintLeft_toRightOf="@+id/imageView"
    android:layout_constraintRight_toRightOf="parent"/>
      
</android.support.constraint.ConstraintLayout>`

**Comment by gopalawasthi123** [comment]
Here is the Code

**Comment by zlannin** [comment]
@gopalawasthi123 Did you add the `Xamarin.Android.Support.ConstraintLayout` nuget package to your project? Also you have `android:layout_constraintLeft_toLeftOf="parent"` and it should be `app:layout_constraintLeft_toLeftOf="parent"`

**Comment by TAnckaerts** [comment]
I recently stumbled on this issue, the workaround still seems to be working.

If this is just a workaround could this be analysed further and see if there is  a more permanent and coherent solution with Native Android.
