### ISSUE TITLE
wrong tag in Arch.Core.Runtime.csproj

### ISSUE THREAD

**Issue by loki666** [xamarin/AndroidSupportComponents#87]
https://github.com/xamarin/AndroidSupportComponents/blob/0a1da9d0179cc0cdca8e4715910bb3759f0b5d88/arch-core/runtime/source/Arch.Core.Runtime.csproj#L71

this tag (and closing tag) should be LibraryProjectZip not EmbeddedJar

**Comment by Redth** [comment]
Thanks, nice catch :)

**Comment by loki666** [comment]
quick question, why isn't this commit showing in master ?
