### ISSUE TITLE
package_resources does not exit

### ISSUE THREAD

**Issue by Goncharuk-Nikita** [xamarin/AndroidSupportComponents#88]
### Xamarin.Android Version (eg: 6.0):
Xamarin.Android SDK   8.1.0.24 (HEAD/9cfa7836b)

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10 Pro v-1709 build-16299.192

### Support Libraries Version (eg: 23.3.0):
Xamarin.Android.Support.Animated.Vector.Drawable - 25.4.0.2
Xamarin.Android.Support.Annotations - 25.4.0.2
Xamarin.Android.Support.Compat - 25.4.0.2
Xamarin.Android.Support.Core.UI - 25.4.0.2
Xamarin.Android.Support.Core.Utils - 25.4.0.2
Xamarin.Android.Support.Design - 25.4.0.2
Xamarin.Android.Support.Fragment - 25.4.0.2
Xamarin.Android.Support.Media.Compat - 25.4.0.2
Xamarin.Android.Support.Transition - 25.4.0.2
Xamarin.Android.Support.v4  - 25.4.0.2
Xamarin.Android.Support.v7.AppCompat - 25.4.0.2
Xamarin.Android.Support.v7.RecyclerView - 25.4.0.2
Xamarin.Android.Support.Vector.Drawable  - 25.4.0.2

### Describe your Issue:
When I start building a project, I get the following error: "package_resources does not exit"

My Steps to Solving (but nothing work):
- checked the names of pictures and their extensions
- Installed all possible variants android SDK, etc.
- reinstalled Android Studio and SDK components
- try to move project in root folder C:\
- try more things...

### Steps to Reproduce (with link to sample solution if possible):
Build project (I got the finished project, and did not do it. An error occurs during build)
Sometimes an error is played during the Build, and sometimes when Deployed . I added the two corresponding OutputLog files.

### Include any relevant Exception Stack traces, build logs, adb logs:
[Csproj_File.txt](https://github.com/xamarin/AndroidSupportComponents/files/1623855/Csproj_File.txt)
[packages.txt](https://github.com/xamarin/AndroidSupportComponents/files/1623858/packages.txt)
[OutputLog_Build.txt](https://github.com/xamarin/AndroidSupportComponents/files/1623859/OutputLog_Build.txt)
[OutputLog_Deploy.txt](https://github.com/xamarin/AndroidSupportComponents/files/1623861/OutputLog_Deploy.txt)

**Comment by Redth** [comment]
I'm not sure this is related to support libraries in particular.  If you look at the aapt task, it does end with `3>Done executing task "Aapt". (TaskId:415)`, without error.  

The failure happens within the `Touch` task, where it's looking for `obj\Debug\android\bin\packaged_resources` and find it doesn't exist.  Given the task is Touch, I'm inclined to believe this is a permissions issue with the `obj/` folder.

I'd recommend trying to delete the entire `obj/` and `bin/` folders, restart your IDE, and try again.

**Comment by Goncharyk** [comment]
I think this is not a problem, because simply DroiddeobzhaDebigandroidevyn is generated only when the build is executed, and a simple cleaning of the project also deletes the files. The error I have is very specific and strange, one time he hammered the project and everything worked, but I decided to check and interrupt him, but he did not want to start any more.

**Comment by newky2k** [comment]
Closing as doesn't appear to be an issue now
