### ISSUE TITLE
Cake MonoApiTools

### ISSUE THREAD

**Issue by JPSiller** [xamarin/AndroidSupportComponents#89]
### Xamarin.Android Version (eg: 6.0):
8

### Operating System & Version (eg: Mac OSX 10.11):
Mac OS Sierra

### Support Libraries Version (eg: 23.3.0):
26

### Describe your Issue:
When running build.sh an error states that Cake.MonoApiTools references Cake 0.17 and it should reference Cake 0.22 or higher. (If you skip the verification there is another error). I'm unable to download the artifacts and dependencies because of this.

### Steps to Reproduce (with link to sample solution if possible):
Download the solution, run the script. 

### Include any relevant Exception Stack traces, build logs, adb logs:The assembly 'Cake.MonoApiTools, Version=1.0.6291.3889, Culture=neutral, PublicKeyToken=null' 
is referencing an older version of Cake.Core (0.17.0). 
This assembly need to reference at least Cake.Core version 0.22.0.

**Comment by Redth** [comment]
You can bypass this by passing `--settings_skipverification=true` to the cake invocation, but we will be updating this other addin soon so it is not required.

**Comment by JPSiller** [comment]
Hi Redth,

Thanks for following up, adding the setting resulted in the following:
One or more errors occurred.
    ApplicationName=‘pod’, CommandLine=‘--version’, CurrentDirectory=‘/Users/psiller/Downloads/AndroidSupportComponents-master’, Native error= Cannot find the specified file

Is this something related to the project itself or am I missing something in my machine?

**Comment by Redth** [comment]
I believe we expect CocoaPods to be installed on Mac... Could you try installing that and see if this works?

**Comment by JPSiller** [comment]
Thanks, I was missing CocoaPods, the script ran successfully.
