### ISSUE TITLE
Could not install package 'Xamarin.Android.Support.Constraint.Layout.Solver 1.0.2.2'

### ISSUE THREAD

**Issue by rjf195** [xamarin/AndroidSupportComponents#91]
### Xamarin.Android Version (eg: 6.0):
7.1.0.41

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10

### Describe your Issue:
When i try install Xamarin Android Constraints Layout package; on Visual Studio 2017, occurrs the next exceptión:

Could not install package 'Xamarin.Android.Support.Constraint.Layout.Solver 1.0.2.2'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Thanks.

**Comment by rjf195** [comment]
If found the solution, upgrade my framework to v7.0, and works

**Comment by newky2k** [comment]
Issue has been resolved
