### ISSUE TITLE
Xamarin.Android.Support.v17.Leanback will not install

### ISSUE THREAD

**Issue by stesvis** [xamarin/AndroidSupportComponents#95]
### Xamarin.Android Version (eg: 6.0): 
8.2.0.15

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10 Home v1709

### Support Libraries Version (eg: 23.3.0):
Trying to install v27.0.2

### Describe your Issue:
The package fails to install

### Steps to Reproduce (with link to sample solution if possible):
install-package Xamarin.Android.Support.v17.Leanback

### Include any relevant Exception Stack traces, build logs, adb logs:

> PM> install-package Xamarin.Android.Support.v17.Leanback
>   CACHE https://api.nuget.org/v3/registration3-gz-semver2/xamarin.android.support.v17.leanback/index.json
>   GET https://dotnet.myget.org/F/aspnetcore-dev/Packages(Id='Xamarin.Android.Support.v17.Leanback',Version='27.0.2')
>   GET http://nuget.syncfusion.com/nuget_xamarin/nuget/getsyncfusionpackages/xamarin/Packages(Id='Xamarin.Android.Support.v17.Leanback',Version='27.0.2')
> Error finding repository for 'https://www.myget.org/F/aspnetvnext/': An error occurred while retrieving package metadata for 'Xamarin.Android.Support.v17.Leanback.27.0.2' from source 'AspnetVnext'.
>   Failed to fetch results from V2 feed at 'https://dotnet.myget.org/F/aspnetcore-dev/Packages(Id='Xamarin.Android.Support.v17.Leanback',Version='27.0.2')' with following message : A task was canceled.
>   A task was canceled.
> Error finding repository for 'http://nuget.syncfusion.com/nuget_xamarin/nuget/getsyncfusionpackages/xamarin': An error occurred while retrieving package metadata for 'Xamarin.Android.Support.v17.Leanback.27.0.2' from source 'Syncfusion_Xamarin'.
>   Failed to fetch results from V2 feed at 'http://nuget.syncfusion.com/nuget_xamarin/nuget/getsyncfusionpackages/xamarin/Packages(Id='Xamarin.Android.Support.v17.Leanback',Version='27.0.2')' with following message : A task was canceled.
>   A task was canceled.
> Restoring packages for H:\Documents\Visual Studio 2017\Projects\BlankApp1\BlankApp1\BlankApp1.Android\BlankApp1.Android.csproj...
> install-package : NU1202: Package Xamarin.Android.Support.v17.Leanback 27.0.2 is not compatible with monoandroid80 (MonoAndroid,Version=v8.0). Package Xamarin.Android.Support.v17.Leanback 27.0.2 supports: monoandroid81 (MonoAndroid,Version=v8.1)
> At line:1 char:1
> + install-package Xamarin.Android.Support.v17.Leanback
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> install-package : Package restore failed. Rolling back package changes for 'BlankApp1.Android'.
> At line:1 char:1
> + install-package Xamarin.Android.Support.v17.Leanback
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Time Elapsed: 00:00:02.1230742

**Comment by Redth** [comment]
Your project needs to use `<TargetFramework>MonoAndroid81</TargetFramework>` to use support libraries v27.x.
