### ISSUE TITLE
27.1.0

### ISSUE THREAD

**Issue by aweFalafelApps** [xamarin/AndroidSupportComponents#98]
Any idea when the latest version will be available?

**Comment by kibotu** [comment]
xamarin reputation tanks a lot missing out on the momentum of support library and play services support and by it's lack of community activity on their official github issue tracker

at this rate they're going to skip 27.1 and jump directly to 28

**Comment by newky2k** [comment]
@aweFalafelApps @kibotu we are working on 27.1.0 at the moment along with looking in to the android x

**Comment by rizaanlakay** [comment]
Any idea when 28.0.1 will be released?
